version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: peer-id
    versions:
    - 0.14.6
    - 0.14.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.28
    - 14.14.32
  - dependency-name: sql-formatter
    versions:
    - 3.1.0
    - 4.0.0
    - 4.0.2
  - dependency-name: ipfs-http-client
    versions:
    - 48.2.2
    - 49.0.1
